### ISSUE TITLE
希望可以把识别框部分和文字分离开？

### ISSUE THREAD

**Issue by Joackk** [xksoft/OcrHelper#7]
现在两者都在一起，在拉长什么的时候两者都会变，有点别扭的感觉，希望可以让两个分离开

**Comment by xiakexiaoyi** [comment]
可以拖动中间控制左边和右边区域的大小哈
![image](https://user-images.githubusercontent.com/24860541/234172929-64927b75-808f-4bd8-a5c0-277869f83aec.png)
